// Generated by export-sheet-to-json.js
// Last updated: 2025-04-14T23:02:08.859Z

export const TOOL_DATA = [
  {
    "id": "1",
    "name": "ChatGPT",
    "source_url": "https://chatgpt.com/",
    "short_description": "OpenAI\u2019s AI assistant for writing, research, and automation.",
    "screenshot_url": "/screenshots/chatgpt.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "2",
    "name": "Claude",
    "source_url": "https://claude.ai/",
    "short_description": "Anthropic\u2019s AI for safe, thoughtful writing and analysis.",
    "screenshot_url": "/screenshots/claude.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "3",
    "name": "Perplexity",
    "source_url": "https://www.perplexity.ai/",
    "short_description": "AI-powered search assistant with real-time answers.",
    "screenshot_url": "/screenshots/perplexity.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "4",
    "name": "Copilot",
    "source_url": "https://copilot.microsoft.com/",
    "short_description": "Microsoft\u2019s AI assistant built into Office and Windows.",
    "screenshot_url": "/screenshots/copilot.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "5",
    "name": "Gemini",
    "source_url": "https://gemini.google.com/",
    "short_description": "Google\u2019s AI assistant for smart search and writing.",
    "screenshot_url": "/screenshots/gemini.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "6",
    "name": "DeepSeek",
    "source_url": "https://www.deepseek.com/",
    "short_description": "Advanced AI model focused on reasoning and accuracy.",
    "screenshot_url": "/screenshots/deepseek.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "7",
    "name": "Jasper",
    "source_url": "https://www.jasper.ai",
    "short_description": "AI writing assistant for marketing and content creation.",
    "screenshot_url": "/screenshots/jasper.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "8",
    "name": "Copy.ai",
    "source_url": "https://www.copy.ai",
    "short_description": "AI tool for emails, product copy, and marketing content.",
    "screenshot_url": "/screenshots/copy.ai.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "9",
    "name": "Rytr",
    "source_url": "https://rytr.me",
    "short_description": "AI writing tool for blogs, emails, and social posts.",
    "screenshot_url": "/screenshots/rytr.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "10",
    "name": "GrammarlyGO",
    "source_url": "https://www.grammarly.com",
    "short_description": "AI that improves writing tone, clarity, and impact.",
    "screenshot_url": "/screenshots/grammarlygo.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "11",
    "name": "Wordtune",
    "source_url": "https://www.wordtune.com",
    "short_description": "AI that rewrites text to sound better and clearer.",
    "screenshot_url": "/screenshots/wordtune.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "12",
    "name": "Sudowrite",
    "source_url": "https://www.sudowrite.com",
    "short_description": "Creative writing AI built for authors and storytellers.",
    "screenshot_url": "/screenshots/sudowrite.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "13",
    "name": "Otter.ai",
    "source_url": "https://otter.ai",
    "short_description": "AI meeting transcription and collaboration tool.",
    "screenshot_url": "/screenshots/otter.ai.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "14",
    "name": "Fireflies.ai",
    "source_url": "https://fireflies.ai",
    "short_description": "Meeting notes, summaries, and search powered by AI.",
    "screenshot_url": "/screenshots/fireflies.ai.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "15",
    "name": "Fathom",
    "source_url": "https://fathom.video",
    "short_description": "Record, transcribe, and summarize meetings instantly.",
    "screenshot_url": "/screenshots/fathom.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "16",
    "name": "tl;dv",
    "source_url": "https://tldv.io",
    "short_description": "AI notes and highlights for Google Meet and Zoom calls.",
    "screenshot_url": "/screenshots/tl;dv.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "17",
    "name": "Avoma",
    "source_url": "https://www.avoma.com",
    "short_description": "AI meeting assistant with notes and CRM integration.",
    "screenshot_url": "/screenshots/avoma.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "18",
    "name": "Sembly",
    "source_url": "https://www.sembly.ai",
    "short_description": "AI meeting assistant with advanced transcription, summaries, and insights.",
    "screenshot_url": "/screenshots/sembly.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "19",
    "name": "Gamma",
    "source_url": "https://gamma.app",
    "short_description": "AI presentation builder with beautiful, modern slides.",
    "screenshot_url": "/screenshots/gamma.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "20",
    "name": "Decktopus",
    "source_url": "https://www.decktopus.com",
    "short_description": "Smart slide generator for fast, branded presentations.",
    "screenshot_url": "/screenshots/decktopus.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "21",
    "name": "Beautiful.ai",
    "source_url": "https://www.beautiful.ai",
    "short_description": "Design professional slides automatically with AI.",
    "screenshot_url": "/screenshots/beautiful.ai.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "22",
    "name": "Pitch",
    "source_url": "https://pitch.com",
    "short_description": "Collaborative presentation software with AI-powered design features.",
    "screenshot_url": "/screenshots/pitch.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "23",
    "name": "Plus AI",
    "source_url": "https://www.plus.ai",
    "short_description": "AI that turns docs into presentation slides quickly.",
    "screenshot_url": "/screenshots/plus_ai.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "24",
    "name": "Canva",
    "source_url": "https://www.canva.com",
    "short_description": "Design tool with AI for graphics, slides, and social posts.",
    "screenshot_url": "/screenshots/canva.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "25",
    "name": "Midjourney",
    "source_url": "https://www.midjourney.com",
    "short_description": "AI that generates stunning images from text prompts.",
    "screenshot_url": "/screenshots/midjourney.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "26",
    "name": "Bing ",
    "source_url": "https://www.bing.com/create",
    "short_description": "Microsoft\u2019s AI image generator using DALL\u00b7E models.",
    "screenshot_url": "/screenshots/bing_.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "27",
    "name": "Synthesia",
    "source_url": "https://www.synthesia.io",
    "short_description": "Create AI avatars and videos from text in minutes.",
    "screenshot_url": "/screenshots/synthesia.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "28",
    "name": "Runway",
    "source_url": "https://runwayml.com",
    "short_description": "AI video editing and content creation platform.",
    "screenshot_url": "/screenshots/runway.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "29",
    "name": "Leonardo AI",
    "source_url": "https://leonardo.ai",
    "short_description": "AI-powered creative platform for generating stunning visual content and artwork.",
    "screenshot_url": "/screenshots/leonardo_ai.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "30",
    "name": "Adobe Firefly",
    "source_url": "https://firefly.adobe.com",
    "short_description": "AI tools for image generation and creative editing.",
    "screenshot_url": "/screenshots/adobe_firefly.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "31",
    "name": "Motion",
    "source_url": "https://www.usemotion.com",
    "short_description": "AI calendar that auto-plans tasks and meetings.",
    "screenshot_url": "/screenshots/motion.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "32",
    "name": "Reclaim.ai",
    "source_url": "https://reclaim.ai",
    "short_description": "Smart scheduling and productivity assistant.",
    "screenshot_url": "/screenshots/reclaim.ai.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "33",
    "name": "Clockwise",
    "source_url": "https://www.getclockwise.com",
    "short_description": "AI that manages team calendars and focuses time.",
    "screenshot_url": "/screenshots/clockwise.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "34",
    "name": "Magical",
    "source_url": "https://www.getmagical.com",
    "short_description": "AI autofill and text expander for repetitive tasks.",
    "screenshot_url": "/screenshots/magical.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "35",
    "name": "Notion AI",
    "source_url": "https://www.notion.so",
    "short_description": "AI-powered notes, docs, and project management.",
    "screenshot_url": "/screenshots/notion_ai.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "36",
    "name": "Sunsama",
    "source_url": "https://sunsama.com",
    "short_description": "Daily planner that aligns goals with your calendar.",
    "screenshot_url": "/screenshots/sunsama.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "37",
    "name": "Elicit",
    "source_url": "https://elicit.org",
    "short_description": "AI research assistant for literature review tasks.",
    "screenshot_url": "/screenshots/elicit.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "38",
    "name": "Phind",
    "source_url": "https://www.phind.com",
    "short_description": "AI search engine for developers and technical research.",
    "screenshot_url": "/screenshots/phind.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "39",
    "name": "Humata",
    "source_url": "https://humata.ai",
    "short_description": "Chat with your documents and get instant answers.",
    "screenshot_url": "/screenshots/humata.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "40",
    "name": "SciSpace",
    "source_url": "https://www.scispace.com",
    "short_description": "AI reader that explains scientific papers simply.",
    "screenshot_url": "/screenshots/scispace.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "41",
    "name": "Genei",
    "source_url": "https://www.genei.io",
    "short_description": "Summarize and analyze research papers with AI.",
    "screenshot_url": "/screenshots/genei.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "42",
    "name": "Wolfram",
    "source_url": "https://www.wolframalpha.com",
    "short_description": "Computational intelligence for math and data.",
    "screenshot_url": "/screenshots/wolfram.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "43",
    "name": "SnackPrompt",
    "source_url": "https://www.snackprompt.com",
    "short_description": "Discover and share ChatGPT prompts instantly.",
    "screenshot_url": "/screenshots/snackprompt.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "44",
    "name": "LearnPrompting",
    "source_url": "https://learnprompting.org",
    "short_description": "Free course to learn prompt engineering basics.",
    "screenshot_url": "/screenshots/learnprompting.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "45",
    "name": "AI Camp",
    "source_url": "https://www.ai-camp.org",
    "short_description": "Learn to build AI apps and products through projects.",
    "screenshot_url": "/screenshots/ai_camp.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "46",
    "name": "FlowGPT",
    "source_url": "https://flowgpt.com",
    "short_description": "Explore and share top-performing ChatGPT prompts.",
    "screenshot_url": "/screenshots/flowgpt.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "47",
    "name": "PromptHero",
    "source_url": "https://www.prompthero.com",
    "short_description": "Library of curated prompts for image and text AIs.",
    "screenshot_url": "/screenshots/prompthero.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "48",
    "name": "SuperPrompt",
    "source_url": "https://superprompt.com",
    "short_description": "Prompt marketplace for AI-generated content.",
    "screenshot_url": "/screenshots/superprompt.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "49",
    "name": "ElevenLabs",
    "source_url": "https://elevenlabs.io",
    "short_description": "Ultra-realistic AI voice generator and dubbing.",
    "screenshot_url": "/screenshots/elevenlabs.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "50",
    "name": "Murf.ai",
    "source_url": "https://murf.ai",
    "short_description": "Voice-over creation platform with AI voices.",
    "screenshot_url": "/screenshots/murf.ai.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "51",
    "name": "Resemble AI",
    "source_url": "https://www.resemble.ai",
    "short_description": "AI voice cloning and speech synthesis platform.",
    "screenshot_url": "/screenshots/resemble_ai.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "52",
    "name": "Speechify",
    "source_url": "https://speechify.com",
    "short_description": "AI tool that reads any text aloud in natural voices.",
    "screenshot_url": "/screenshots/speechify.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "53",
    "name": "Bland.ai",
    "source_url": "https://www.bland.ai",
    "short_description": "AI voice agents for automated phone conversations.",
    "screenshot_url": "/screenshots/bland.ai.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "54",
    "name": "Play.ht",
    "source_url": "https://play.ht",
    "short_description": "Text-to-speech tool with lifelike AI voices.",
    "screenshot_url": "/screenshots/play.ht.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "55",
    "name": "Sports Innovation Lab",
    "source_url": "https://sportsilab.com",
    "short_description": "Insights and strategy platform for sports brands.",
    "screenshot_url": "/screenshots/sports_innovation_lab.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Fan Intelligence"
  },
  {
    "id": "56",
    "name": "Spalk",
    "source_url": "https://www.spalk.tv/ai/",
    "short_description": "AI audio commentary generator & translator for live sports.",
    "screenshot_url": "/screenshots/spalk.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Advertising & Media"
  },
  {
    "id": "57",
    "name": "PixelScope",
    "source_url": "https://pxscope.com",
    "short_description": "AI-enhanced visual analytics for sports broadcasts.",
    "screenshot_url": "/screenshots/pixelscope.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Advertising & Media"
  },
  {
    "id": "58",
    "name": "Reely",
    "source_url": "https://reelyai.com/",
    "short_description": "Auto-generate sports highlights with AI editing.",
    "screenshot_url": "/screenshots/reely.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Advertising & Media"
  },
  {
    "id": "59",
    "name": "Veritone",
    "source_url": "https://veritone.com",
    "short_description": "AI tools for media, licensing, and content tagging.",
    "screenshot_url": "/screenshots/veritone.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Advertising & Media"
  },
  {
    "id": "60",
    "name": "Supponor",
    "source_url": "https://supponor.com",
    "short_description": "Virtual advertising overlays for live sports.",
    "screenshot_url": "/screenshots/supponor.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Advertising & Media"
  },
  {
    "id": "61",
    "name": "Veo",
    "source_url": "https://www.veo.co",
    "short_description": "AI-powered cameras for filming and analyzing games.",
    "screenshot_url": "/screenshots/veo.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Advertising & Media"
  },
  {
    "id": "62",
    "name": "Sponix",
    "source_url": "https://sponixtech.com",
    "short_description": "Real-time virtual ads and immersive sports replays.",
    "screenshot_url": "/screenshots/sponix.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Advertising & Media"
  },
  {
    "id": "63",
    "name": "Play Anywhere",
    "source_url": "https://playanywhere.com/",
    "short_description": "Stream and monetize live sports from any location.",
    "screenshot_url": "/screenshots/play_anywhere.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Advertising & Media"
  },
  {
    "id": "64",
    "name": "Greenfly",
    "source_url": "https://www.greenfly.com",
    "short_description": "AI media distribution for athletes and teams.",
    "screenshot_url": "/screenshots/greenfly.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Advertising & Media"
  },
  {
    "id": "65",
    "name": "Machina Sports",
    "source_url": "https://machina.gg",
    "short_description": "AI performance tracking for training and gameplay.",
    "screenshot_url": "/screenshots/machina_sports.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Creative & Personalization"
  },
  {
    "id": "66",
    "name": "Mobius Labs",
    "source_url": "https://www.mobiuslabs.com",
    "short_description": "AI-powered visual search and tagging engine.",
    "screenshot_url": "/screenshots/mobius_labs.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Creative & Personalization"
  },
  {
    "id": "67",
    "name": "Magnifi",
    "source_url": "https://magnifi.ai",
    "short_description": "Automates highlight generation from live content.",
    "screenshot_url": "/screenshots/magnifi.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Creative & Personalization"
  },
  {
    "id": "68",
    "name": "Artlist",
    "source_url": "https://artlist.io",
    "short_description": "Royalty-free music and footage with AI curation.",
    "screenshot_url": "/screenshots/artlist.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Creative & Personalization"
  },
  {
    "id": "69",
    "name": "WSC Sports",
    "source_url": "https://wsc-sports.com",
    "short_description": "AI-driven video highlights and sports content.",
    "screenshot_url": "/screenshots/wsc_sports.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Creative & Personalization"
  },
  {
    "id": "70",
    "name": "Beyond Sports",
    "source_url": "https://beyondsports.nl",
    "short_description": "Data visualization and simulations for sports.",
    "screenshot_url": "/screenshots/beyond_sports.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Creative & Personalization"
  },
  {
    "id": "71",
    "name": "Synthesia",
    "source_url": "https://www.synthesia.io",
    "short_description": "Create AI avatars and videos from text in minutes.",
    "screenshot_url": "/screenshots/synthesia.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Creative & Personalization"
  },
  {
    "id": "72",
    "name": "IBM (Watson)",
    "source_url": "https://www.ibm.com/sports",
    "short_description": "Enterprise AI tools including sports data insights.",
    "screenshot_url": "/screenshots/ibm_(watson).png",
    "category": "None",
    "type": "enterprise",
    "sector": "Creative & Personalization"
  },
  {
    "id": "73",
    "name": "Wehave",
    "source_url": "https://wehave.io",
    "short_description": "AI-driven talent and creator sponsorship matching.",
    "screenshot_url": "/screenshots/wehave.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Sponsorship & Revenue"
  },
  {
    "id": "74",
    "name": "SponsWatch",
    "source_url": "https://sponswatch.com",
    "short_description": "Track and analyze brand exposure in sports media.",
    "screenshot_url": "/screenshots/sponswatch.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Sponsorship & Revenue"
  },
  {
    "id": "75",
    "name": "Providential Media Group",
    "source_url": "https://providentialmedia.com",
    "short_description": "Sports content studio with AI production workflows.",
    "screenshot_url": "/screenshots/providential_media_group.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Sponsorship & Revenue"
  },
  {
    "id": "76",
    "name": "Relo Metrics",
    "source_url": "https://relometrics.com",
    "short_description": "AI that measures sponsorship impact in real-time.",
    "screenshot_url": "/screenshots/relo_metrics.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Sponsorship & Revenue"
  },
  {
    "id": "77",
    "name": "Blinkfire Analytics",
    "source_url": "https://blinkfire.com",
    "short_description": "AI-powered sponsorship and social media valuation.",
    "screenshot_url": "/screenshots/blinkfire_analytics.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Sponsorship & Revenue"
  },
  {
    "id": "78",
    "name": "SponsorPulse",
    "source_url": "https://sponsorpulse.com",
    "short_description": "Tracks fan engagement to value sponsorships.",
    "screenshot_url": "/screenshots/sponsorpulse.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Sponsorship & Revenue"
  },
  {
    "id": "79",
    "name": "Nielsen Sports",
    "source_url": "https://nielsensports.com",
    "short_description": "Global leader in sports media and fan analytics.",
    "screenshot_url": "/screenshots/nielsen_sports.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Sponsorship & Revenue"
  },
  {
    "id": "80",
    "name": "Second Spectrum",
    "source_url": "https://secondspectrum.com",
    "short_description": "AI-driven tracking and analytics for sports teams.",
    "screenshot_url": "/screenshots/second_spectrum.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Measurement & Analytics"
  },
  {
    "id": "81",
    "name": "Stats Perform",
    "source_url": "https://statsperform.com",
    "short_description": "Sports data and AI insights for performance and betting.",
    "screenshot_url": "/screenshots/stats_perform.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Measurement & Analytics"
  },
  {
    "id": "82",
    "name": "Hawk-Eye Innovations",
    "source_url": "https://hawkeyeinnovations.com",
    "short_description": "Vision and replay tech for officiating and broadcast.",
    "screenshot_url": "/screenshots/hawk-eye_innovations.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Measurement & Analytics"
  },
  {
    "id": "83",
    "name": "Zone7",
    "source_url": "https://zone7.ai",
    "short_description": "Predictive AI to reduce athlete injury risk.",
    "screenshot_url": "/screenshots/zone7.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Measurement & Analytics"
  },
  {
    "id": "84",
    "name": "Kitman Labs",
    "source_url": "https://kitmanlabs.com",
    "short_description": "Sports performance platform powered by AI.",
    "screenshot_url": "/screenshots/kitman_labs.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Measurement & Analytics"
  },
  {
    "id": "85",
    "name": "Soccerment",
    "source_url": "https://soccerment.com",
    "short_description": "Advanced football analytics and data scouting.",
    "screenshot_url": "/screenshots/soccerment.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Measurement & Analytics"
  },
  {
    "id": "86",
    "name": "RespoVision",
    "source_url": "https://respo.vision",
    "short_description": "AI visual tracking and player performance insights.",
    "screenshot_url": "/screenshots/respovision.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Measurement & Analytics"
  },
  {
    "id": "87",
    "name": "Sportlogiq",
    "source_url": "https://sportlogiq.com",
    "short_description": "AI-powered sports data and game analysis platform.",
    "screenshot_url": "/screenshots/sportlogiq.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Measurement & Analytics"
  },
  {
    "id": "88",
    "name": "Zapier",
    "source_url": "https://zapier.com/app/home",
    "short_description": "Connect apps and automate workflows without code.",
    "screenshot_url": "/screenshots/zapier.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "89",
    "name": "CrewAI",
    "source_url": "https://www.crewai.com/",
    "short_description": "Create multi-agent AI systems to automate workflows.",
    "screenshot_url": "/screenshots/crewai.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "90",
    "name": "Cognosys",
    "source_url": "https://www.cognosys.ai/",
    "short_description": "One-click deployable autonomous GPT-based agents.",
    "screenshot_url": "/screenshots/cognosys.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "91",
    "name": "Superagent",
    "source_url": "https://superagent.sh/",
    "short_description": "Build and run AI agents with tools and memory.",
    "screenshot_url": "/screenshots/superagent.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "92",
    "name": "Replit",
    "source_url": "https://replit.com/",
    "short_description": "Online coding workspace with collaborative AI tools.",
    "screenshot_url": "/screenshots/replit.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "93",
    "name": "BabyAGI",
    "source_url": "https://github.com/yoheinakajima/babyagi",
    "short_description": "Task-driven autonomous agent framework for complex problem solving.",
    "screenshot_url": "/screenshots/babyagi.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "94",
    "name": "LangChain",
    "source_url": "https://www.langchain.com/",
    "short_description": "Framework to build AI agents and apps with LLMs.",
    "screenshot_url": "/screenshots/langchain.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "95",
    "name": "Dust.tt",
    "source_url": "https://dust.tt/",
    "short_description": "AI platform to create personalized assistant workflows.",
    "screenshot_url": "/screenshots/dust.tt.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "96",
    "name": "Flowise",
    "source_url": "https://flowiseai.com/",
    "short_description": "Visual low-code builder for LLM-powered agents.",
    "screenshot_url": "/screenshots/flowise.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "97",
    "name": "PromptLayer",
    "source_url": "https://promptlayer.com/",
    "short_description": "Track and manage prompts in production LLM apps.",
    "screenshot_url": "/screenshots/promptlayer.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "98",
    "name": "LlamaIndex",
    "source_url": "https://www.llamaindex.ai/",
    "short_description": "Framework to connect LLMs with external data.",
    "screenshot_url": "/screenshots/llamaindex.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "99",
    "name": "Haystack",
    "source_url": "https://haystack.deepset.ai",
    "short_description": "Open-source LLM orchestration framework for building AI applications.",
    "screenshot_url": "/screenshots/haystack.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "100",
    "name": "Hugging Face",
    "source_url": "https://huggingface.co/",
    "short_description": "Hub for open-source AI models, datasets, and demos.",
    "screenshot_url": "/screenshots/hugging_face.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "101",
    "name": "Replicate",
    "source_url": "https://replicate.com/",
    "short_description": "Run and host open-source machine learning models.",
    "screenshot_url": "/screenshots/replicate.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "102",
    "name": "OpenPipe",
    "source_url": "https://www.openpipe.ai/",
    "short_description": "Fine-tune and deploy fast, affordable GPT models.",
    "screenshot_url": "/screenshots/openpipe.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "103",
    "name": "Modal",
    "source_url": "https://modal.com/",
    "short_description": "Serverless compute platform for ML and data workflows.",
    "screenshot_url": "/screenshots/modal.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "104",
    "name": "Cohere",
    "source_url": "https://cohere.com",
    "short_description": "Enterprise LLM platform with powerful language models and APIs.",
    "screenshot_url": "/screenshots/cohere.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "105",
    "name": "Together.ai",
    "source_url": "https://www.together.ai/",
    "short_description": "Open-source LLMs and inference infrastructure.",
    "screenshot_url": "/screenshots/together.ai.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "106",
    "name": "Replit Ghostwriter",
    "source_url": "https://replit.com/",
    "short_description": "AI coding assistant built into Replit\u2019s IDE.",
    "screenshot_url": "/screenshots/replit_ghostwriter.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "107",
    "name": "CodeGeeX",
    "source_url": "https://codegeex.cn/en-US",
    "short_description": "Multilingual AI coding assistant supporting 20+ programming languages.",
    "screenshot_url": "/screenshots/codegeex.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "108",
    "name": "Cursor",
    "source_url": "https://www.cursor.so/",
    "short_description": "Collaborative code editor with built-in AI assistant.",
    "screenshot_url": "/screenshots/cursor.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "109",
    "name": "Codeium",
    "source_url": "https://www.codeium.com/",
    "short_description": "Free AI code completion for all major editors.",
    "screenshot_url": "/screenshots/codeium.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "110",
    "name": "Continue",
    "source_url": "https://continue.dev/",
    "short_description": "VS Code extension for AI code suggestions.",
    "screenshot_url": "/screenshots/continue.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "111",
    "name": "Amazon CodeWhisperer",
    "source_url": "https://aws.amazon.com/codewhisperer/",
    "short_description": "AI coding companion from AWS with security scanning and code suggestions.",
    "screenshot_url": "/screenshots/amazon_codewhisperer.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "112",
    "name": "Pinecone",
    "source_url": "https://www.pinecone.io/",
    "short_description": "Vector database for semantic search and RAG apps.",
    "screenshot_url": "/screenshots/pinecone.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "113",
    "name": "Weaviate",
    "source_url": "https://weaviate.io/",
    "short_description": "Scalable vector database with hybrid search.",
    "screenshot_url": "/screenshots/weaviate.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "114",
    "name": "Chroma",
    "source_url": "https://www.trychroma.com/",
    "short_description": "Open-source embedding database for LLM apps.",
    "screenshot_url": "/screenshots/chroma.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "115",
    "name": "Zep",
    "source_url": "https://getzep.com/",
    "short_description": "Vector store with memory for LLM-powered agents.",
    "screenshot_url": "/screenshots/zep.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "116",
    "name": "Milvus",
    "source_url": "https://milvus.io/",
    "short_description": "Vector database for similarity search at scale.",
    "screenshot_url": "/screenshots/milvus.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "117",
    "name": "Qdrant",
    "source_url": "https://qdrant.tech/",
    "short_description": "Open-source vector DB for AI applications.",
    "screenshot_url": "/screenshots/qdrant.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  }
];